export type Bank = {
  name: string;
  url: string;
  icon: string;
  description: string;
  country: string;
  flag: string;
};

const banks: Bank[] = [
  {
    name: "Airwallex",
    url: "https://airwallex.com",
    icon: "https://www.google.com/s2/favicons?domain=airwallex.com&sz=64",
    description: "Global financial platform for businesses to collect, hold, and send money across 150+ countries.",
    country: "Australia",
    flag: "🇦🇺",
  },
  {
    name: "Bank of America",
    url: "https://bankofamerica.com",
    icon: "https://www.google.com/s2/favicons?domain=bankofamerica.com&sz=64",
    description: "Major US financial institution offering banking, credit cards, loans, and investment services.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Bluevine",
    url: "https://bluevine.com",
    icon: "https://www.google.com/s2/favicons?domain=bluevine.com&sz=64",
    description: "Online banking for small businesses with high-yield checking accounts and lines of credit.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "BNP Paribas",
    url: "https://bnpparibas.fr",
    icon: "https://www.google.com/s2/favicons?domain=bnpparibas.fr&sz=64",
    description: "France's largest bank, offering personal and corporate banking, insurance, and investment services worldwide.",
    country: "France",
    flag: "🇫🇷",
  },
  {
    name: "Boursobank",
    url: "https://boursobank.com",
    icon: "https://www.google.com/s2/favicons?domain=boursobank.com&sz=64",
    description: "France's leading online bank, offering no-fee accounts, savings, credit cards, and investment products.",
    country: "France",
    flag: "🇫🇷",
  },
  {
    name: "Capital One",
    url: "https://capitalone.com",
    icon: "https://www.google.com/s2/favicons?domain=capitalone.com&sz=64",
    description: "Digital-first US bank known for credit cards, no-fee checking accounts, and auto loans.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Chase",
    url: "https://chase.com",
    icon: "https://www.google.com/s2/favicons?domain=chase.com&sz=64",
    description: "One of the largest US banks offering personal and business banking, credit cards, and investments.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Citibank",
    url: "https://citi.com",
    icon: "https://www.google.com/s2/favicons?domain=citi.com&sz=64",
    description: "Global bank with strong US presence, known for credit cards, consumer banking, and wealth management.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "HSBC",
    url: "https://hsbc.com",
    icon: "https://www.google.com/s2/favicons?domain=hsbc.com&sz=64",
    description: "One of the world's largest banks offering personal, business, and private banking across 60+ countries.",
    country: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    name: "Mercury",
    url: "https://mercury.com",
    icon: "https://www.google.com/s2/favicons?domain=mercury.com&sz=64",
    description: "Banking built for startups and tech companies, with powerful API access and no monthly fees.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "N26 Personal",
    url: "https://n26.com",
    icon: "https://www.google.com/s2/favicons?domain=n26.com&sz=64",
    description: "European mobile bank with fee-free accounts, instant notifications, and global money transfers.",
    country: "Germany",
    flag: "🇩🇪",
  },
  {
    name: "Payoneer",
    url: "https://payoneer.com",
    icon: "https://www.google.com/s2/favicons?domain=payoneer.com&sz=64",
    description: "Global payment platform for freelancers and businesses to receive and send international payments.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Qonto",
    url: "https://qonto.com",
    icon: "https://www.google.com/s2/favicons?domain=qonto.com&sz=64",
    description: "Business banking platform built for freelancers and SMEs, with integrated invoicing and accounting.",
    country: "France",
    flag: "🇫🇷",
  },
  {
    name: "Relay",
    url: "https://relayfi.com",
    icon: "https://www.google.com/s2/favicons?domain=relayfi.com&sz=64",
    description: "Business banking platform with multi-account cash flow management and no transaction fees.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Revolut Business",
    url: "https://business.revolut.com",
    icon: "https://www.google.com/s2/favicons?domain=revolut.com&sz=64",
    description: "Business account with multi-currency wallets, expense management, and global payments.",
    country: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    name: "Revolut Personal",
    url: "https://revolut.com",
    icon: "https://www.google.com/s2/favicons?domain=revolut.com&sz=64",
    description: "Personal banking app with multi-currency accounts, spending insights, budgeting, and fee-free international transfers.",
    country: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    name: "SHINE",
    url: "https://shine.fr",
    icon: "https://www.google.com/s2/favicons?domain=shine.fr&sz=64",
    description: "Business banking for French freelancers and micro-businesses with invoicing, VAT tracking, and company registration.",
    country: "France",
    flag: "🇫🇷",
  },
  {
    name: "Wells Fargo",
    url: "https://wellsfargo.com",
    icon: "https://www.google.com/s2/favicons?domain=wellsfargo.com&sz=64",
    description: "Diversified US bank providing consumer banking, mortgages, investments, and business services.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Wise Business",
    url: "https://wise.com/gb/business",
    icon: "https://www.google.com/s2/favicons?domain=wise.com&sz=64",
    description: "Low-cost international business transfers with multi-currency accounts and real exchange rates.",
    country: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    name: "Wise Personal",
    url: "https://wise.com",
    icon: "https://www.google.com/s2/favicons?domain=wise.com&sz=64",
    description: "Personal multi-currency account for receiving, holding, and sending money internationally at real exchange rates.",
    country: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    name: "Dukascopy",
    url: "https://dukascopy.com",
    icon: "https://www.google.com/s2/favicons?domain=dukascopy.com&sz=64",
    description: "Swiss bank and forex broker offering multi-currency IBAN, trading accounts, and a prepaid Visa card.",
    country: "Switzerland",
    flag: "🇨🇭",
  },
  {
    name: "First Finance Bank",
    url: "https://firstfinancebank.com",
    icon: "https://www.google.com/s2/favicons?domain=firstfinancebank.com&sz=64",
    description: "Community bank offering personal and business banking services including checking, savings, and loans.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "FV Bank",
    url: "https://fvbank.us",
    icon: "https://www.google.com/s2/favicons?domain=fvbank.us&sz=64",
    description: "US federally chartered bank for international clients and crypto businesses, offering FDIC-insured accounts and wire transfers.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "GrabRFi",
    url: "https://grabrfi.com",
    icon: "https://www.google.com/s2/favicons?domain=grabrfi.com&sz=64",
    description: "Digital banking platform offering global accounts, payments, and financial tools for individuals and businesses.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Jeeves",
    url: "https://jeeves.app",
    icon: "https://www.google.com/s2/favicons?domain=jeeves.app&sz=64",
    description: "Corporate card and spend management platform for startups with no FX fees, multi-currency payouts, and global coverage.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Nubank",
    url: "https://nubank.com.br",
    icon: "https://www.google.com/s2/favicons?domain=nubank.com.br&sz=64",
    description: "Brazil's largest neobank and one of the world's biggest fintechs, offering no-fee accounts, credit cards, and investments.",
    country: "Brazil",
    flag: "🇧🇷",
  },
  {
    name: "OneSafe",
    url: "https://onesafe.io",
    icon: "https://www.google.com/s2/favicons?domain=onesafe.io&sz=64",
    description: "Crypto-friendly business banking with multi-currency accounts, IBAN, and instant payments for global businesses.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Ugly.cash",
    url: "https://ugly.cash",
    icon: "https://www.google.com/s2/favicons?domain=ugly.cash&sz=64",
    description: "Stablecoin-powered payment platform for fast, low-cost international transfers without traditional banking fees.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Utoppia",
    url: "https://utoppia.com",
    icon: "https://www.google.com/s2/favicons?domain=utoppia.com&sz=64",
    description: "Digital US bank designed for Latin American professionals, offering US accounts, wire transfers, and multi-currency access.",
    country: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Zenus Bank",
    url: "https://zenusbank.com",
    icon: "https://www.google.com/s2/favicons?domain=zenusbank.com&sz=64",
    description: "US-chartered bank open to international applicants — get a US Visa credit card and bank account without a US address.",
    country: "United States",
    flag: "🇺🇸",
  },
];

export default banks;
