export type App = {
  name: string;
  url: string;
  icon: string;
  tags: string[];
  description: string;
  brand: string;
};

const catalog: App[] = [
  // AI
  {
    name: "Botpress",
    url: "https://botpress.com",
    icon: "https://www.google.com/s2/favicons?domain=botpress.com&sz=64",
    tags: ["AI"],
    description: "Open-source platform for building, deploying, and managing AI chatbots and autonomous agents.",
    brand: "Botpress",
  },
  {
    name: "Claude",
    url: "https://claude.ai",
    icon: "https://www.google.com/s2/favicons?domain=claude.ai&sz=64",
    tags: ["AI"],
    description: "AI assistant for writing, coding, and analysis.",
    brand: "Anthropic",
  },
  {
    name: "ChatGPT",
    url: "https://chatgpt.com",
    icon: "https://www.google.com/s2/favicons?domain=chatgpt.com&sz=64",
    tags: ["AI"],
    description: "AI conversational assistant for writing, coding, research, and problem-solving.",
    brand: "OpenAI",
  },
  {
    name: "Gemini",
    url: "https://gemini.google.com",
    icon: "https://www.google.com/s2/favicons?domain=gemini.google.com&sz=64",
    tags: ["AI"],
    description: "Google's AI assistant for multimodal tasks including text, images, and code.",
    brand: "Google",
  },
  {
    name: "Fireflies",
    url: "https://fireflies.ai",
    icon: "https://www.google.com/s2/favicons?domain=fireflies.ai&sz=64",
    tags: ["AI"],
    description: "AI meeting assistant that records, transcribes, and analyzes conversations.",
    brand: "Fireflies",
  },
  {
    name: "Fathom",
    url: "https://fathom.video",
    icon: "https://www.google.com/s2/favicons?domain=fathom.video&sz=64",
    tags: ["AI"],
    description: "AI meeting recorder and note-taker that automatically summarizes calls.",
    brand: "Fathom",
  },
  {
    name: "WhisprFlow",
    url: "https://whisprflow.com",
    icon: "https://www.google.com/s2/favicons?domain=whisprflow.com&sz=64",
    tags: ["AI"],
    description: "AI-powered voice workflow automation tool for hands-free productivity.",
    brand: "WhisprFlow",
  },
  // Automation
  {
    name: "n8n",
    url: "https://n8n.io",
    icon: "https://www.google.com/s2/favicons?domain=n8n.io&sz=64",
    tags: ["Automation"],
    description: "Open-source workflow automation tool for connecting apps and APIs with code flexibility.",
    brand: "n8n",
  },
  {
    name: "Make",
    url: "https://make.com",
    icon: "https://www.google.com/s2/favicons?domain=make.com&sz=64",
    tags: ["Automation"],
    description: "Visual no-code platform for building automated workflows between apps.",
    brand: "Make",
  },
  {
    name: "Phantombuster",
    url: "https://phantombuster.com",
    icon: "https://www.google.com/s2/favicons?domain=phantombuster.com&sz=64",
    tags: ["Automation"],
    description: "Cloud-based automation tool for scraping data and automating social media actions.",
    brand: "Phantombuster",
  },
  // Dev
  {
    name: "WordPress",
    url: "https://wordpress.com",
    icon: "https://www.google.com/s2/favicons?domain=wordpress.com&sz=64",
    tags: ["Dev"],
    description: "Open-source CMS powering 40% of the web — build and manage websites, blogs, and online stores with thousands of plugins and themes.",
    brand: "WordPress",
  },
  {
    name: "GitHub",
    url: "https://github.com",
    icon: "https://www.google.com/s2/favicons?domain=github.com&sz=64",
    tags: ["Dev"],
    description: "Web platform for hosting and collaborating on code repositories.",
    brand: "GitHub",
  },
  {
    name: "GitHub Desktop",
    url: "https://desktop.github.com",
    icon: "https://www.google.com/s2/favicons?domain=desktop.github.com&sz=64",
    tags: ["Dev"],
    description: "Visual Git client for managing repositories without the command line.",
    brand: "GitHub",
  },
  {
    name: "Antigravity IDE",
    url: "https://antigravity.google",
    icon: "https://www.google.com/s2/favicons?domain=antigravity.google&sz=64",
    tags: ["Dev"],
    description: "AI-native code editor built for agentic development.",
    brand: "Google",
  },
  {
    name: "Vercel",
    url: "https://vercel.com",
    icon: "https://www.google.com/s2/favicons?domain=vercel.com&sz=64",
    tags: ["Dev"],
    description: "Cloud platform for deploying and hosting frontend projects and serverless functions.",
    brand: "Vercel",
  },
  {
    name: "Apify",
    url: "https://apify.com",
    icon: "https://www.google.com/s2/favicons?domain=apify.com&sz=64",
    tags: ["Dev"],
    description: "Web scraping and browser automation platform for extracting web data at scale.",
    brand: "Apify",
  },
  {
    name: "Algolia",
    url: "https://algolia.com",
    icon: "https://www.google.com/s2/favicons?domain=algolia.com&sz=64",
    tags: ["Dev"],
    description: "Search and discovery API for building fast, relevant search experiences.",
    brand: "Algolia",
  },
  {
    name: "Hookdeck",
    url: "https://hookdeck.com",
    icon: "https://www.google.com/s2/favicons?domain=hookdeck.com&sz=64",
    tags: ["Dev"],
    description: "Webhook infrastructure for receiving, transforming, and routing events reliably.",
    brand: "Hookdeck",
  },
  {
    name: "LangChain",
    url: "https://langchain.com",
    icon: "https://www.google.com/s2/favicons?domain=langchain.com&sz=64",
    tags: ["Dev"],
    description: "Framework for building LLM-powered applications and AI agents.",
    brand: "LangChain",
  },
  {
    name: "Firecrawl",
    url: "https://firecrawl.dev",
    icon: "https://www.google.com/s2/favicons?domain=firecrawl.dev&sz=64",
    tags: ["Dev"],
    description: "Web scraping API that converts any website into clean data for AI applications.",
    brand: "Firecrawl",
  },
  {
    name: "Multilogin",
    url: "https://multilogin.com",
    icon: "https://www.google.com/s2/favicons?domain=multilogin.com&sz=64",
    tags: ["Dev"],
    description: "Multi-account browser for managing separate profiles with unique fingerprints.",
    brand: "Multilogin",
  },
  {
    name: "Bolt",
    url: "https://bolt.new",
    icon: "https://www.google.com/s2/favicons?domain=bolt.new&sz=64",
    tags: ["Dev"],
    description: "AI-powered full-stack web development environment that generates, runs, and deploys apps from a prompt.",
    brand: "StackBlitz",
  },
  {
    name: "Pinecone",
    url: "https://pinecone.io",
    icon: "https://www.google.com/s2/favicons?domain=pinecone.io&sz=64",
    tags: ["Dev"],
    description: "Managed vector database for building AI applications with semantic search and similarity matching at scale.",
    brand: "Pinecone",
  },
  {
    name: "Rider",
    url: "https://rider.jetbrains.com",
    icon: "https://www.google.com/s2/favicons?domain=rider.jetbrains.com&sz=64",
    tags: ["Dev"],
    description: "Cross-platform .NET and game development IDE with deep C#, Unity, and Unreal Engine support.",
    brand: "JetBrains",
  },
  {
    name: "Webhook.site",
    url: "https://webhook.site",
    icon: "https://www.google.com/s2/favicons?domain=webhook.site&sz=64",
    tags: ["Dev"],
    description: "Instant webhook and HTTP request inspector for testing, debugging, and automating integrations.",
    brand: "Webhook.site",
  },
  {
    name: "21st.dev",
    url: "https://21st.dev",
    icon: "https://www.google.com/s2/favicons?domain=21st.dev&sz=64",
    tags: ["Dev"],
    description: "Component marketplace for shipping polished UI faster with ready-made React components.",
    brand: "21st.dev",
  },
  {
    name: "Supabase",
    url: "https://supabase.com",
    icon: "https://www.google.com/s2/favicons?domain=supabase.com&sz=64",
    tags: ["Dev"],
    description: "Open-source Firebase alternative with a Postgres database, auth, storage, and realtime subscriptions.",
    brand: "Supabase",
  },
  // Design
  {
    name: "Adobe Photoshop",
    url: "https://photoshop.adobe.com",
    icon: "https://www.google.com/s2/favicons?domain=photoshop.adobe.com&sz=64",
    tags: ["Design"],
    description: "Industry-standard raster graphics editor for photo editing, compositing, and digital art.",
    brand: "Adobe",
  },
  {
    name: "Adobe After Effects",
    url: "https://adobe.com/products/aftereffects.html",
    icon: "https://www.google.com/s2/favicons?domain=adobe.com&sz=64",
    tags: ["Design"],
    description: "Motion graphics and visual effects software for film, TV, video, and web.",
    brand: "Adobe",
  },
  {
    name: "Affinity",
    url: "https://affinity.serif.com",
    icon: "https://www.google.com/s2/favicons?domain=affinity.serif.com&sz=64",
    tags: ["Design"],
    description: "Professional creative suite (Photo, Designer, Publisher) — a one-time purchase alternative to Adobe.",
    brand: "Serif",
  },
  {
    name: "Aseprite",
    url: "https://aseprite.org",
    icon: "https://www.google.com/s2/favicons?domain=aseprite.org&sz=64",
    tags: ["Design"],
    description: "Pixel art editor and animation tool for creating sprites, tilesets, and retro-style games.",
    brand: "Aseprite",
  },
  {
    name: "Blender",
    url: "https://blender.org",
    icon: "https://www.google.com/s2/favicons?domain=blender.org&sz=64",
    tags: ["Design"],
    description: "Free and open-source 3D creation suite for modeling, animation, rendering, and video editing.",
    brand: "Blender Foundation",
  },
  {
    name: "Canva",
    url: "https://canva.com",
    icon: "https://www.google.com/s2/favicons?domain=canva.com&sz=64",
    tags: ["Design"],
    description: "Drag-and-drop design platform for creating social media graphics, presentations, and marketing materials.",
    brand: "Canva",
  },
  {
    name: "CapCut",
    url: "https://capcut.com",
    icon: "https://www.google.com/s2/favicons?domain=capcut.com&sz=64",
    tags: ["Design"],
    description: "AI-powered video editor for creating short-form content with effects, templates, and auto-captions.",
    brand: "ByteDance",
  },
  {
    name: "Whimsical",
    url: "https://whimsical.com",
    icon: "https://www.google.com/s2/favicons?domain=whimsical.com&sz=64",
    tags: ["Design"],
    description: "Visual workspace for flowcharts, wireframes, mind maps, and documents.",
    brand: "Whimsical",
  },
  {
    name: "Lucid",
    url: "https://lucid.app",
    icon: "https://www.google.com/s2/favicons?domain=lucid.app&sz=64",
    tags: ["Design"],
    description: "Visual collaboration suite for diagramming, whiteboarding, and team alignment.",
    brand: "Lucid",
  },
  {
    name: "Excalidraw",
    url: "https://excalidraw.com",
    icon: "https://www.google.com/s2/favicons?domain=excalidraw.com&sz=64",
    tags: ["Design"],
    description: "Open-source virtual whiteboard for sketching diagrams with a hand-drawn feel.",
    brand: "Excalidraw",
  },
  {
    name: "Godly",
    url: "https://godly.website",
    icon: "https://www.google.com/s2/favicons?domain=godly.website&sz=64",
    tags: ["Design"],
    description: "Curated gallery of the best web design references and inspirations.",
    brand: "Godly",
  },
  {
    name: "OBS Studio",
    url: "https://obsproject.com",
    icon: "https://www.google.com/s2/favicons?domain=obsproject.com&sz=64",
    tags: ["Design"],
    description: "Free and open-source software for video recording and live streaming with scene composition, audio mixing, and real-time encoding.",
    brand: "OBS Project",
  },
  // Marketing
  {
    name: "Shopify",
    url: "https://shopify.com",
    icon: "https://www.google.com/s2/favicons?domain=shopify.com&sz=64",
    tags: ["Marketing"],
    description: "All-in-one commerce platform to build, launch, and scale online stores with payments, shipping, and analytics built in.",
    brand: "Shopify",
  },
  {
    name: "ClickFunnels",
    url: "https://clickfunnels.com",
    icon: "https://www.google.com/s2/favicons?domain=clickfunnels.com&sz=64",
    tags: ["Marketing"],
    description: "Sales funnel and landing page builder for capturing leads and converting them into customers.",
    brand: "ClickFunnels",
  },
  {
    name: "Leadmagic",
    url: "https://leadmagic.com",
    icon: "https://www.google.com/s2/favicons?domain=leadmagic.com&sz=64",
    tags: ["Marketing"],
    description: "B2B data enrichment tool for finding verified email addresses and company data from LinkedIn profiles.",
    brand: "Leadmagic",
  },
  {
    name: "Leadsie",
    url: "https://leadsie.com",
    icon: "https://www.google.com/s2/favicons?domain=leadsie.com&sz=64",
    tags: ["Marketing"],
    description: "Link-based tool that lets agencies collect client access to Facebook, Instagram, and Google Ads accounts.",
    brand: "Leadsie",
  },
  {
    name: "Skool",
    url: "https://skool.com",
    icon: "https://www.google.com/s2/favicons?domain=skool.com&sz=64",
    tags: ["Marketing"],
    description: "Community and online course platform for creators to build and monetize their audience.",
    brand: "Skool",
  },
  {
    name: "Tardigrada",
    url: "https://tardigrada.io",
    icon: "https://www.google.com/s2/favicons?domain=tardigrada.io&sz=64",
    tags: ["Dev"],
    description: "Real US phone numbers on demand — carrier-backed SIM numbers (not VoIP) that receive SMS and pass verification checks that virtual numbers fail. REST API + webhooks.",
    brand: "Tardigrada",
  },
  {
    name: "Instantly",
    url: "https://instantly.ai",
    icon: "https://www.google.com/s2/favicons?domain=instantly.ai&sz=64",
    tags: ["Marketing"],
    description: "AI-powered cold email outreach and lead generation platform.",
    brand: "Instantly",
  },
  {
    name: "Apollo",
    url: "https://apollo.io",
    icon: "https://www.google.com/s2/favicons?domain=apollo.io&sz=64",
    tags: ["Marketing"],
    description: "Sales intelligence platform for finding leads, contacts, and running outreach.",
    brand: "Apollo",
  },
  {
    name: "AutoIGDM",
    url: "https://autoigdm.com",
    icon: "https://www.google.com/s2/favicons?domain=autoigdm.com&sz=64",
    tags: ["Marketing"],
    description: "Automated Instagram DM outreach tool for lead generation and prospecting.",
    brand: "AutoIGDM",
  },
  // Productivity
  {
    name: "Notion",
    url: "https://notion.so",
    icon: "https://www.google.com/s2/favicons?domain=notion.so&sz=64",
    tags: ["Productivity"],
    description: "All-in-one workspace for notes, docs, wikis, and project management.",
    brand: "Notion",
  },
  {
    name: "Gmail",
    url: "https://mail.google.com",
    icon: "https://www.google.com/s2/favicons?domain=mail.google.com&sz=64",
    tags: ["Productivity"],
    description: "Google's email service with powerful search and smart inbox features.",
    brand: "Google",
  },
  {
    name: "Loom",
    url: "https://loom.com",
    icon: "https://www.google.com/s2/favicons?domain=loom.com&sz=64",
    tags: ["Productivity"],
    description: "Screen and video recording tool for async communication and walkthroughs.",
    brand: "Loom",
  },
  {
    name: "Typeform",
    url: "https://typeform.com",
    icon: "https://www.google.com/s2/favicons?domain=typeform.com&sz=64",
    tags: ["Productivity"],
    description: "Interactive form and survey builder with a conversational interface.",
    brand: "Typeform",
  },
  {
    name: "PandaDoc",
    url: "https://pandadoc.com",
    icon: "https://www.google.com/s2/favicons?domain=pandadoc.com&sz=64",
    tags: ["Productivity"],
    description: "Document automation for proposals, contracts, and legally-binding e-signatures.",
    brand: "PandaDoc",
  },
  {
    name: "Cal.com",
    url: "https://cal.com",
    icon: "https://www.google.com/s2/favicons?domain=cal.com&sz=64",
    tags: ["Productivity"],
    description: "Open-source scheduling platform for booking meetings without back-and-forth.",
    brand: "Cal.com",
  },
  {
    name: "Calendly",
    url: "https://calendly.com",
    icon: "https://www.google.com/s2/favicons?domain=calendly.com&sz=64",
    tags: ["Productivity"],
    description: "Scheduling automation tool that lets others book time on your calendar easily.",
    brand: "Calendly",
  },
  {
    name: "Rize",
    url: "https://rize.io",
    icon: "https://www.google.com/s2/favicons?domain=rize.io&sz=64",
    tags: ["Productivity"],
    description: "AI-powered time tracker that categorizes your work and helps you focus.",
    brand: "Rize",
  },
  {
    name: "Toggl",
    url: "https://toggl.com",
    icon: "https://www.google.com/s2/favicons?domain=toggl.com&sz=64",
    tags: ["Productivity"],
    description: "Simple one-click time tracking for freelancers and teams.",
    brand: "Toggl",
  },
  {
    name: "Harvest",
    url: "https://getharvest.com",
    icon: "https://www.google.com/s2/favicons?domain=getharvest.com&sz=64",
    tags: ["Productivity"],
    description: "Time tracking and invoicing tool built for project-based billing.",
    brand: "Harvest",
  },
  {
    name: "Presentify",
    url: "https://presentify.app",
    icon: "https://www.google.com/s2/favicons?domain=presentify.app&sz=64",
    tags: ["Productivity"],
    description: "Mac app for annotating your screen during live presentations, calls, and screen recordings.",
    brand: "Presentify",
  },
  {
    name: "Auphoric",
    url: "https://auphoric.com",
    icon: "https://www.google.com/s2/favicons?domain=auphoric.com&sz=64",
    tags: ["Productivity"],
    description: "Podcast and audio content management platform for creators and teams.",
    brand: "Auphoric",
  },
  {
    name: "Google Workspace",
    url: "https://workspace.google.com",
    icon: "https://www.google.com/s2/favicons?domain=workspace.google.com&sz=64",
    tags: ["Productivity"],
    description: "Google's business productivity suite including Gmail, Docs, Drive, Meet, and Calendar.",
    brand: "Google",
  },
  {
    name: "Doola",
    url: "https://doola.com",
    icon: "https://www.google.com/s2/favicons?domain=doola.com&sz=64",
    tags: ["Productivity"],
    description: "Business formation and compliance platform for launching LLCs, C-corps, and sole proprietorships.",
    brand: "Doola",
  },
  {
    name: "Deel",
    url: "https://deel.com",
    icon: "https://www.google.com/s2/favicons?domain=deel.com&sz=64",
    tags: ["Productivity"],
    description: "Global payroll, HR, and compliance platform for hiring and paying international employees and contractors.",
    brand: "Deel",
  },
  {
    name: "Upwork",
    url: "https://upwork.com",
    icon: "https://www.google.com/s2/favicons?domain=upwork.com&sz=64",
    tags: ["Productivity"],
    description: "Global freelancing platform to find, hire, and collaborate with independent professionals.",
    brand: "Upwork",
  },
  {
    name: "Uber",
    url: "https://uber.com",
    icon: "https://www.google.com/s2/favicons?domain=uber.com&sz=64",
    tags: ["Productivity"],
    description: "Ride-hailing and delivery platform available in 70+ countries for business and personal travel.",
    brand: "Uber",
  },
  // Security
  {
    name: "1Password",
    url: "https://1password.com",
    icon: "https://www.google.com/s2/favicons?domain=1password.com&sz=64",
    tags: ["Security"],
    description: "Password manager and secure digital vault for individuals and teams.",
    brand: "1Password",
  },
  {
    name: "Proton Pass",
    url: "https://pass.proton.me",
    icon: "https://www.google.com/s2/favicons?domain=pass.proton.me&sz=64",
    tags: ["Security"],
    description: "End-to-end encrypted password manager from Proton, with zero-knowledge privacy.",
    brand: "Proton",
  },
  // Social
  {
    name: "Discord",
    url: "https://discord.com",
    icon: "https://www.google.com/s2/favicons?domain=discord.com&sz=64",
    tags: ["Social"],
    description: "Voice, video, and text chat platform for communities and teams.",
    brand: "Discord",
  },
  {
    name: "Instagram",
    url: "https://instagram.com",
    icon: "https://www.google.com/s2/favicons?domain=instagram.com&sz=64",
    tags: ["Social"],
    description: "Photo and video sharing social network with stories, reels, and direct messaging.",
    brand: "Meta",
  },
  {
    name: "Snapchat",
    url: "https://snapchat.com",
    icon: "https://www.google.com/s2/favicons?domain=snapchat.com&sz=64",
    tags: ["Social"],
    description: "Ephemeral photo and video messaging app with stories, lenses, and Snap Map.",
    brand: "Snap Inc.",
  },
  {
    name: "TikTok",
    url: "https://tiktok.com",
    icon: "https://www.google.com/s2/favicons?domain=tiktok.com&sz=64",
    tags: ["Social"],
    description: "Short-form video platform for creating and discovering viral content.",
    brand: "ByteDance",
  },
  {
    name: "Tinder",
    url: "https://tinder.com",
    icon: "https://www.google.com/s2/favicons?domain=tinder.com&sz=64",
    tags: ["Social"],
    description: "Dating app for swiping, matching, and connecting with people nearby.",
    brand: "Match Group",
  },
  {
    name: "WhatsApp",
    url: "https://whatsapp.com",
    icon: "https://www.google.com/s2/favicons?domain=whatsapp.com&sz=64",
    tags: ["Social"],
    description: "Encrypted messaging, voice, and video calling app.",
    brand: "Meta",
  },
  {
    name: "X",
    url: "https://x.com",
    icon: "https://www.google.com/s2/favicons?domain=x.com&sz=64",
    tags: ["Social"],
    description: "Real-time social network for news, discussion, and public conversation. Formerly Twitter.",
    brand: "X Corp.",
  },
  // Storage
  {
    name: "OneDrive",
    url: "https://onedrive.live.com",
    icon: "https://www.google.com/s2/favicons?domain=onedrive.live.com&sz=64",
    tags: ["Storage"],
    description: "Microsoft's cloud storage service integrated with Office 365 for syncing and sharing files across devices.",
    brand: "Microsoft",
  },
  {
    name: "Dropbox",
    url: "https://dropbox.com",
    icon: "https://www.google.com/s2/favicons?domain=dropbox.com&sz=64",
    tags: ["Storage"],
    description: "Cloud storage and file sharing service for syncing files across devices.",
    brand: "Dropbox",
  },
  {
    name: "Google Drive",
    url: "https://drive.google.com",
    icon: "https://www.google.com/s2/favicons?domain=drive.google.com&sz=64",
    tags: ["Storage"],
    description: "Cloud storage and file sharing integrated with Google Docs, Sheets, and Slides.",
    brand: "Google",
  },
  // Entertainment
  {
    name: "YouTube",
    url: "https://youtube.com",
    icon: "https://www.google.com/s2/favicons?domain=youtube.com&sz=64",
    tags: ["Entertainment"],
    description: "Video streaming platform for watching and sharing content worldwide.",
    brand: "Google",
  },
  {
    name: "Spotify",
    url: "https://spotify.com",
    icon: "https://www.google.com/s2/favicons?domain=spotify.com&sz=64",
    tags: ["Entertainment"],
    description: "Music and podcast streaming service with millions of tracks.",
    brand: "Spotify",
  },
  // Shopping
  {
    name: "Carrefour",
    url: "https://carrefour.fr",
    icon: "https://www.google.com/s2/favicons?domain=carrefour.fr&sz=64",
    tags: ["Shopping"],
    description: "One of Europe's largest retail chains offering groceries, electronics, and household goods online and in-store.",
    brand: "Carrefour",
  },
  {
    name: "Amazon",
    url: "https://amazon.com",
    icon: "https://www.google.com/s2/favicons?domain=amazon.com&sz=64",
    tags: ["Shopping"],
    description: "Online marketplace for shopping, streaming, and cloud services.",
    brand: "Amazon",
  },
  // Learning
  {
    name: "Baselang",
    url: "https://baselang.com",
    icon: "https://www.google.com/s2/favicons?domain=baselang.com&sz=64",
    tags: ["Learning"],
    description: "Subscription language learning service with unlimited 1-on-1 tutoring sessions for immersive language acquisition.",
    brand: "Baselang",
  },
  {
    name: "italki",
    url: "https://italki.com",
    icon: "https://www.google.com/s2/favicons?domain=italki.com&sz=64",
    tags: ["Learning"],
    description: "Online language learning marketplace to book lessons with professional teachers and community tutors worldwide.",
    brand: "italki",
  },
  // Game Dev
  {
    name: "Godot",
    url: "https://godotengine.org",
    icon: "https://www.google.com/s2/favicons?domain=godotengine.org&sz=64",
    tags: ["Game Dev"],
    description: "Free and open-source game engine for 2D and 3D games with its own scripting language (GDScript) and C# support.",
    brand: "Godot Engine",
  },
  {
    name: "Unreal Engine",
    url: "https://unrealengine.com",
    icon: "https://www.google.com/s2/favicons?domain=unrealengine.com&sz=64",
    tags: ["Game Dev"],
    description: "High-fidelity 3D game engine by Epic Games, used in AAA game development, film, and real-time visualization.",
    brand: "Epic Games",
  },
  {
    name: "Unity",
    url: "https://unity.com",
    icon: "https://www.google.com/s2/favicons?domain=unity.com&sz=64",
    tags: ["Game Dev"],
    description: "Cross-platform game engine for creating 2D and 3D games, AR/VR applications, and interactive experiences.",
    brand: "Unity Technologies",
  },
  // Gaming
  {
    name: "Steam",
    url: "https://store.steampowered.com",
    icon: "https://www.google.com/s2/favicons?domain=steampowered.com&sz=64",
    tags: ["Gaming"],
    description: "The world's largest PC gaming platform — buy, download, and launch games with cloud saves and community features.",
    brand: "Valve",
  },
  {
    name: "DeSmuME",
    url: "https://desmume.org",
    icon: "https://www.google.com/s2/favicons?domain=desmume.org&sz=64",
    tags: ["Gaming"],
    description: "Open-source Nintendo DS emulator for playing DS games on desktop.",
    brand: "DeSmuME",
  },
  // Food
  {
    name: "Uber Eats",
    url: "https://ubereats.com",
    icon: "https://www.google.com/s2/favicons?domain=ubereats.com&sz=64",
    tags: ["Food"],
    description: "Food delivery platform connecting you with local restaurants and grocery stores for on-demand delivery or pickup.",
    brand: "Uber",
  },
  {
    name: "Deliveroo",
    url: "https://deliveroo.fr",
    icon: "https://www.google.com/s2/favicons?domain=deliveroo.fr&sz=64",
    tags: ["Food"],
    description: "Food delivery service partnering with local restaurants and grocers for fast, trackable delivery to your door.",
    brand: "Deliveroo",
  },
  // Travel
  {
    name: "ADA",
    url: "https://ada.fr",
    icon: "https://www.google.com/s2/favicons?domain=ada.fr&sz=64",
    tags: ["Travel"],
    description: "French car rental network with 350+ agencies across France offering short and long-term vehicle hire at competitive rates.",
    brand: "ADA",
  },
];

export default catalog;
