export type App = {
  name: string;
  url: string;
  icon: string;
  tags: string[];
  description: string;
  brand: string;
};

const catalog: App[] = [
  // AI
  {
    name: "Claude",
    url: "https://claude.ai",
    icon: "https://www.google.com/s2/favicons?domain=claude.ai&sz=64",
    tags: ["AI"],
    description: "AI assistant for writing, coding, and analysis.",
    brand: "Anthropic",
  },
  {
    name: "ChatGPT",
    url: "https://chatgpt.com",
    icon: "https://www.google.com/s2/favicons?domain=chatgpt.com&sz=64",
    tags: ["AI"],
    description: "AI conversational assistant for writing, coding, research, and problem-solving.",
    brand: "OpenAI",
  },
  {
    name: "Gemini",
    url: "https://gemini.google.com",
    icon: "https://www.google.com/s2/favicons?domain=gemini.google.com&sz=64",
    tags: ["AI"],
    description: "Google's AI assistant for multimodal tasks including text, images, and code.",
    brand: "Google",
  },
  {
    name: "Fireflies",
    url: "https://fireflies.ai",
    icon: "https://www.google.com/s2/favicons?domain=fireflies.ai&sz=64",
    tags: ["AI"],
    description: "AI meeting assistant that records, transcribes, and analyzes conversations.",
    brand: "Fireflies",
  },
  {
    name: "Fathom",
    url: "https://fathom.video",
    icon: "https://www.google.com/s2/favicons?domain=fathom.video&sz=64",
    tags: ["AI"],
    description: "AI meeting recorder and note-taker that automatically summarizes calls.",
    brand: "Fathom",
  },
  {
    name: "WhisprFlow",
    url: "https://whisprflow.com",
    icon: "https://www.google.com/s2/favicons?domain=whisprflow.com&sz=64",
    tags: ["AI"],
    description: "AI-powered voice workflow automation tool for hands-free productivity.",
    brand: "WhisprFlow",
  },
  // Automation
  {
    name: "n8n",
    url: "https://n8n.io",
    icon: "https://www.google.com/s2/favicons?domain=n8n.io&sz=64",
    tags: ["Automation"],
    description: "Open-source workflow automation tool for connecting apps and APIs with code flexibility.",
    brand: "n8n",
  },
  {
    name: "Make",
    url: "https://make.com",
    icon: "https://www.google.com/s2/favicons?domain=make.com&sz=64",
    tags: ["Automation"],
    description: "Visual no-code platform for building automated workflows between apps.",
    brand: "Make",
  },
  {
    name: "Phantombuster",
    url: "https://phantombuster.com",
    icon: "https://www.google.com/s2/favicons?domain=phantombuster.com&sz=64",
    tags: ["Automation"],
    description: "Cloud-based automation tool for scraping data and automating social media actions.",
    brand: "Phantombuster",
  },
  // Dev
  {
    name: "GitHub",
    url: "https://github.com",
    icon: "https://www.google.com/s2/favicons?domain=github.com&sz=64",
    tags: ["Dev"],
    description: "Web platform for hosting and collaborating on code repositories.",
    brand: "GitHub",
  },
  {
    name: "GitHub Desktop",
    url: "https://desktop.github.com",
    icon: "https://www.google.com/s2/favicons?domain=desktop.github.com&sz=64",
    tags: ["Dev"],
    description: "Visual Git client for managing repositories without the command line.",
    brand: "GitHub",
  },
  {
    name: "Antigravity IDE",
    url: "https://antigravity.google",
    icon: "https://www.google.com/s2/favicons?domain=antigravity.google&sz=64",
    tags: ["Dev"],
    description: "AI-native code editor built for agentic development.",
    brand: "Google",
  },
  {
    name: "Vercel",
    url: "https://vercel.com",
    icon: "https://www.google.com/s2/favicons?domain=vercel.com&sz=64",
    tags: ["Dev"],
    description: "Cloud platform for deploying and hosting frontend projects and serverless functions.",
    brand: "Vercel",
  },
  {
    name: "Apify",
    url: "https://apify.com",
    icon: "https://www.google.com/s2/favicons?domain=apify.com&sz=64",
    tags: ["Dev"],
    description: "Web scraping and browser automation platform for extracting web data at scale.",
    brand: "Apify",
  },
  {
    name: "Algolia",
    url: "https://algolia.com",
    icon: "https://www.google.com/s2/favicons?domain=algolia.com&sz=64",
    tags: ["Dev"],
    description: "Search and discovery API for building fast, relevant search experiences.",
    brand: "Algolia",
  },
  {
    name: "Hookdeck",
    url: "https://hookdeck.com",
    icon: "https://www.google.com/s2/favicons?domain=hookdeck.com&sz=64",
    tags: ["Dev"],
    description: "Webhook infrastructure for receiving, transforming, and routing events reliably.",
    brand: "Hookdeck",
  },
  {
    name: "LangChain",
    url: "https://langchain.com",
    icon: "https://www.google.com/s2/favicons?domain=langchain.com&sz=64",
    tags: ["Dev"],
    description: "Framework for building LLM-powered applications and AI agents.",
    brand: "LangChain",
  },
  {
    name: "Firecrawl",
    url: "https://firecrawl.dev",
    icon: "https://www.google.com/s2/favicons?domain=firecrawl.dev&sz=64",
    tags: ["Dev"],
    description: "Web scraping API that converts any website into clean data for AI applications.",
    brand: "Firecrawl",
  },
  {
    name: "Multilogin",
    url: "https://multilogin.com",
    icon: "https://www.google.com/s2/favicons?domain=multilogin.com&sz=64",
    tags: ["Dev"],
    description: "Multi-account browser for managing separate profiles with unique fingerprints.",
    brand: "Multilogin",
  },
  {
    name: "21st.dev",
    url: "https://21st.dev",
    icon: "https://www.google.com/s2/favicons?domain=21st.dev&sz=64",
    tags: ["Dev"],
    description: "Component marketplace for shipping polished UI faster with ready-made React components.",
    brand: "21st.dev",
  },
  // Design
  {
    name: "Whimsical",
    url: "https://whimsical.com",
    icon: "https://www.google.com/s2/favicons?domain=whimsical.com&sz=64",
    tags: ["Design"],
    description: "Visual workspace for flowcharts, wireframes, mind maps, and documents.",
    brand: "Whimsical",
  },
  {
    name: "Lucid",
    url: "https://lucid.app",
    icon: "https://www.google.com/s2/favicons?domain=lucid.app&sz=64",
    tags: ["Design"],
    description: "Visual collaboration suite for diagramming, whiteboarding, and team alignment.",
    brand: "Lucid",
  },
  {
    name: "Excalidraw",
    url: "https://excalidraw.com",
    icon: "https://www.google.com/s2/favicons?domain=excalidraw.com&sz=64",
    tags: ["Design"],
    description: "Open-source virtual whiteboard for sketching diagrams with a hand-drawn feel.",
    brand: "Excalidraw",
  },
  {
    name: "Godly",
    url: "https://godly.website",
    icon: "https://www.google.com/s2/favicons?domain=godly.website&sz=64",
    tags: ["Design"],
    description: "Curated gallery of the best web design references and inspirations.",
    brand: "Godly",
  },
  // Marketing
  {
    name: "Instantly",
    url: "https://instantly.ai",
    icon: "https://www.google.com/s2/favicons?domain=instantly.ai&sz=64",
    tags: ["Marketing"],
    description: "AI-powered cold email outreach and lead generation platform.",
    brand: "Instantly",
  },
  {
    name: "Apollo",
    url: "https://apollo.io",
    icon: "https://www.google.com/s2/favicons?domain=apollo.io&sz=64",
    tags: ["Marketing"],
    description: "Sales intelligence platform for finding leads, contacts, and running outreach.",
    brand: "Apollo",
  },
  {
    name: "AutoIGDM",
    url: "https://autoigdm.com",
    icon: "https://www.google.com/s2/favicons?domain=autoigdm.com&sz=64",
    tags: ["Marketing"],
    description: "Automated Instagram DM outreach tool for lead generation and prospecting.",
    brand: "AutoIGDM",
  },
  // Productivity
  {
    name: "Notion",
    url: "https://notion.so",
    icon: "https://www.google.com/s2/favicons?domain=notion.so&sz=64",
    tags: ["Productivity"],
    description: "All-in-one workspace for notes, docs, wikis, and project management.",
    brand: "Notion",
  },
  {
    name: "Gmail",
    url: "https://mail.google.com",
    icon: "https://www.google.com/s2/favicons?domain=mail.google.com&sz=64",
    tags: ["Productivity"],
    description: "Google's email service with powerful search and smart inbox features.",
    brand: "Google",
  },
  {
    name: "Loom",
    url: "https://loom.com",
    icon: "https://www.google.com/s2/favicons?domain=loom.com&sz=64",
    tags: ["Productivity"],
    description: "Screen and video recording tool for async communication and walkthroughs.",
    brand: "Loom",
  },
  {
    name: "Typeform",
    url: "https://typeform.com",
    icon: "https://www.google.com/s2/favicons?domain=typeform.com&sz=64",
    tags: ["Productivity"],
    description: "Interactive form and survey builder with a conversational interface.",
    brand: "Typeform",
  },
  {
    name: "PandaDoc",
    url: "https://pandadoc.com",
    icon: "https://www.google.com/s2/favicons?domain=pandadoc.com&sz=64",
    tags: ["Productivity"],
    description: "Document automation for proposals, contracts, and legally-binding e-signatures.",
    brand: "PandaDoc",
  },
  {
    name: "Cal.com",
    url: "https://cal.com",
    icon: "https://www.google.com/s2/favicons?domain=cal.com&sz=64",
    tags: ["Productivity"],
    description: "Open-source scheduling platform for booking meetings without back-and-forth.",
    brand: "Cal.com",
  },
  {
    name: "Calendly",
    url: "https://calendly.com",
    icon: "https://www.google.com/s2/favicons?domain=calendly.com&sz=64",
    tags: ["Productivity"],
    description: "Scheduling automation tool that lets others book time on your calendar easily.",
    brand: "Calendly",
  },
  {
    name: "Rize",
    url: "https://rize.io",
    icon: "https://www.google.com/s2/favicons?domain=rize.io&sz=64",
    tags: ["Productivity"],
    description: "AI-powered time tracker that categorizes your work and helps you focus.",
    brand: "Rize",
  },
  {
    name: "Toggl",
    url: "https://toggl.com",
    icon: "https://www.google.com/s2/favicons?domain=toggl.com&sz=64",
    tags: ["Productivity"],
    description: "Simple one-click time tracking for freelancers and teams.",
    brand: "Toggl",
  },
  {
    name: "Harvest",
    url: "https://getharvest.com",
    icon: "https://www.google.com/s2/favicons?domain=getharvest.com&sz=64",
    tags: ["Productivity"],
    description: "Time tracking and invoicing tool built for project-based billing.",
    brand: "Harvest",
  },
  {
    name: "Auphoric",
    url: "https://auphoric.com",
    icon: "https://www.google.com/s2/favicons?domain=auphoric.com&sz=64",
    tags: ["Productivity"],
    description: "Podcast and audio content management platform for creators and teams.",
    brand: "Auphoric",
  },
  // Security
  {
    name: "1Password",
    url: "https://1password.com",
    icon: "https://www.google.com/s2/favicons?domain=1password.com&sz=64",
    tags: ["Security"],
    description: "Password manager and secure digital vault for individuals and teams.",
    brand: "1Password",
  },
  {
    name: "Proton Pass",
    url: "https://pass.proton.me",
    icon: "https://www.google.com/s2/favicons?domain=pass.proton.me&sz=64",
    tags: ["Security"],
    description: "End-to-end encrypted password manager from Proton, with zero-knowledge privacy.",
    brand: "Proton",
  },
  // Social
  {
    name: "Discord",
    url: "https://discord.com",
    icon: "https://www.google.com/s2/favicons?domain=discord.com&sz=64",
    tags: ["Social"],
    description: "Voice, video, and text chat platform for communities and teams.",
    brand: "Discord",
  },
  {
    name: "WhatsApp",
    url: "https://whatsapp.com",
    icon: "https://www.google.com/s2/favicons?domain=whatsapp.com&sz=64",
    tags: ["Social"],
    description: "Encrypted messaging, voice, and video calling app.",
    brand: "Meta",
  },
  // Storage
  {
    name: "Dropbox",
    url: "https://dropbox.com",
    icon: "https://www.google.com/s2/favicons?domain=dropbox.com&sz=64",
    tags: ["Storage"],
    description: "Cloud storage and file sharing service for syncing files across devices.",
    brand: "Dropbox",
  },
  {
    name: "Google Drive",
    url: "https://drive.google.com",
    icon: "https://www.google.com/s2/favicons?domain=drive.google.com&sz=64",
    tags: ["Storage"],
    description: "Cloud storage and file sharing integrated with Google Docs, Sheets, and Slides.",
    brand: "Google",
  },
  // Entertainment
  {
    name: "YouTube",
    url: "https://youtube.com",
    icon: "https://www.google.com/s2/favicons?domain=youtube.com&sz=64",
    tags: ["Entertainment"],
    description: "Video streaming platform for watching and sharing content worldwide.",
    brand: "Google",
  },
  {
    name: "Spotify",
    url: "https://spotify.com",
    icon: "https://www.google.com/s2/favicons?domain=spotify.com&sz=64",
    tags: ["Entertainment"],
    description: "Music and podcast streaming service with millions of tracks.",
    brand: "Spotify",
  },
  // Shopping
  {
    name: "Amazon",
    url: "https://amazon.com",
    icon: "https://www.google.com/s2/favicons?domain=amazon.com&sz=64",
    tags: ["Shopping"],
    description: "Online marketplace for shopping, streaming, and cloud services.",
    brand: "Amazon",
  },
  // Gaming
  {
    name: "DeSmuME",
    url: "https://desmume.org",
    icon: "https://www.google.com/s2/favicons?domain=desmume.org&sz=64",
    tags: ["Gaming"],
    description: "Open-source Nintendo DS emulator for playing DS games on desktop.",
    brand: "DeSmuME",
  },
];

export default catalog;
